### ISSUE TITLE
FEATURE: Add option to hide caches

### ISSUE THREAD

**Issue by erkenes** [flownative/neos-cachemanagement#8]
It should be possible to hide specific caches if we unset the configuration:

```yaml
Flownative:
  Neos:
    CacheManagement:
      caches:
        Neos_Fusion_Content: ~
        Flow_Mvc_Routing_Route: ~
        Flow_Mvc_Routing_Resolve: ~
```

The current behaviour just removes the label

![Image](https://github.com/user-attachments/assets/c8ff518e-0167-4144-996d-ef3a4c76d57f)
